-- AlterTable
ALTER TABLE "Space" ALTER COLUMN "name" SET DATA TYPE VARCHAR(100);
ALTER TABLE "Space" ALTER COLUMN "reference" SET DATA TYPE VARCHAR(500);
ALTER TABLE "Space" ALTER COLUMN "description" SET DATA TYPE VARCHAR(500);
